apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: with-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: 76f88a75-c0e3-4d57-8f81-cd6eaef25c96
    keyvaultName: kv-2024070102
    cloudName: "" # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: secret             # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 3ee688ca-6ea4-4c8e-90dd-17a233844683 # The tenant ID of the key vault
  secretObjects: # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
    - data:
        - key: secret # data field to populate
          objectName: secret # name of the mounted content to sync; this could be the object name or the object alias
      secretName: my-secret # name of the Kubernetes secret object
      type: Opaque
